CourseProject
GeorgeUG02/Android-Popular-libraries pull request #8
Opened 2021-08-27 11:24 UTC by GeorgeUG02

2021-08-31 19:02 UTC, PeterBukhal-Geekbrains approved these changes
Отлично продолжай. Есть проблемы над которыми нужно еще поработать.

2021-08-31 19:02 UTC, PeterBukhal-Geekbrains commented on CourseProject/app/build.gradle
> +    implementation 'com.google.dagger:dagger:2.24'
старая версия dagger2 обнови до 2.37

2021-08-31 19:02 UTC, PeterBukhal-Geekbrains commented on CourseProject/app/src/main/java/com/example/courseproject/ApiModule.kt
> +    fun baseUrl(): String = "https://api.rawg.io"
графомания какая то как по мне)

2021-08-31 19:02 UTC, PeterBukhal-Geekbrains commented on CourseProject/app/src/main/java/com/example/courseproject/ApiModule.kt
> +    fun api(@Named("baseUrl") baseUrl: String, gson: Gson): IDataSource =
Общее соглашение для наименования фабрик такое: 
* `@Provides` -> `fun provide...()`
* `@Binds` -> `fun bind...()`
Думаю не стоит тут городить что то свое.

2021-08-31 19:02 UTC, PeterBukhal-Geekbrains commented on CourseProject/app/src/main/java/com/example/courseproject/ApiModule.kt
> +    fun gson() = GsonBuilder()
Общее соглашение для наименования фабрик такое: 
* `@Provides` -> `fun provide...()`
* `@Binds` -> `fun bind...()`
Думаю не стоит тут городить что то свое.

2021-08-31 19:02 UTC, PeterBukhal-Geekbrains commented on CourseProject/app/src/main/java/com/example/courseproject/ApiModule.kt
> +    fun api2(@Named("baseUrl") baseUrl: String, gson: Gson): IDataSource2 =
Общее соглашение для наименования фабрик такое: 
* `@Provides` -> `fun provide...()`
* `@Binds` -> `fun bind...()`
Думаю не стоит тут городить что то свое.

2021-08-31 19:02 UTC, PeterBukhal-Geekbrains commented on CourseProject/app/src/main/java/com/example/courseproject/ApiModule.kt
> +    @Singleton
Подумай стоит ли везде добавлять `@Singleton`, так как для stateless зависимостей это совершенно лишняя операция. напоминаю что еще есть `@Reusable` и noscope зависимости.

2021-08-31 19:02 UTC, PeterBukhal-Geekbrains commented on CourseProject/app/src/main/java/com/example/courseproject/App.kt
> +        lateinit var instance: App
Это дольше не нужно, это костыль.

2021-08-31 19:02 UTC, PeterBukhal-Geekbrains commented on CourseProject/app/src/main/java/com/example/courseproject/App.kt
> +    lateinit var appComponent: AppComponent
Все таки такие вещи лучше делать через `Component.Builder`, а не хранить в модуле ссылки на типы, он для этого не предназначен как бы. Или сделать еще одну фабрику именно для этого типа в самом модуле.

2021-08-31 19:02 UTC, PeterBukhal-Geekbrains commented on CourseProject/app/src/main/java/com/example/courseproject/App.kt
> +class App : Application() {
dagger-android думаю тут не помешает, особенно потому что в этой либе решается часть не очень красивых моментов Dagger 2 при использовании его в Android.

2021-08-31 19:02 UTC, PeterBukhal-Geekbrains commented on CourseProject/app/src/main/java/com/example/courseproject/AppComponent.kt
> +    fun inject(mainActivity: MainActivity)
Посмотри код урока 7, все таки там это сделано лучше с использованием аннотации `@ContributeAndroidInjector`, в твоем варианте придется в компонент каждый раз вносить изменения когда нужно добавить новый экран или презентер.

2021-08-31 19:02 UTC, PeterBukhal-Geekbrains commented on CourseProject/app/src/main/java/com/example/courseproject/BackButtonListener.kt
> +    fun backPressed(): Boolean
в Cicerone возврат назад и так работает прекрасно без всяких) просто убери и используй правильныйе команды router`a

2021-08-31 19:02 UTC, PeterBukhal-Geekbrains commented on CourseProject/app/src/main/java/com/example/courseproject/CacheModule.kt
> +    @Singleton
Подумай стоит ли везде добавлять `@Singleton`, так как для stateless зависимостей это совершенно лишняя операция. напоминаю что еще есть `@Reusable` и noscope зависимости.

2021-08-31 19:02 UTC, PeterBukhal-Geekbrains commented on CourseProject/app/src/main/java/com/example/courseproject/CacheModule.kt
> +    fun gameDescriptionCache(database: Database): IGameDescriptionCache =
Общее соглашение для наименования фабрик такое: 
* `@Provides` -> `fun provide...()`
* `@Binds` -> `fun bind...()`
Думаю не стоит тут городить что то свое.

2021-08-31 19:02 UTC, PeterBukhal-Geekbrains commented on CourseProject/app/src/main/java/com/example/courseproject/CacheModule.kt
> +    @Provides
Везде где возможно следует отдавать предпочтение `@Binds` перед `@Provides` и инжектить в конструктор.

2021-08-31 19:02 UTC, PeterBukhal-Geekbrains commented on CourseProject/app/src/main/java/com/example/courseproject/GameDescriptionFragment.kt
> +            arguments = Bundle().apply {
Правильней не создавать новый `Bundle`, а пользоваться фабрикой `bundleOf` будет чуть эффективней)

2021-08-31 19:02 UTC, PeterBukhal-Geekbrains commented on CourseProject/app/src/main/java/com/example/courseproject/GameDescriptionFragment.kt
> +        fun newInstance(id:Int) = GameDescriptionFragment().apply {
При создании объектов используя фабрики нужно возвращать максимально базовый тип в иерархии наследования если такая имеется, то есть делать восходящее преобразование. В данном случае к `Fragment`, см. `FragmentScreen` из Cicerone. Это дает больше возможностей по изменению реализации, и явно указывает на то что не следует использовать или ссылаться на тип конкретного фрагмента.

2021-08-31 19:02 UTC, PeterBukhal-Geekbrains commented on CourseProject/app/src/main/java/com/example/courseproject/GameDescriptionFragment.kt
> +    val presenter: GameDescriptionPresenter by moxyPresenter {
Инкапсуляция нарушена, должно быть с модификатором `private`

2021-08-31 19:02 UTC, PeterBukhal-Geekbrains commented on CourseProject/app/src/main/java/com/example/courseproject/GameDescriptionFragment.kt
> +    override fun backPressed() = presenter.backPressed()
в Cicerone возврат назад и так работает прекрасно без всяких) просто убери и используй правильныйе команды router`a

2021-08-31 19:02 UTC, PeterBukhal-Geekbrains commented on CourseProject/app/src/main/java/com/example/courseproject/GameDescriptionPresenter.kt
> +    @Inject lateinit var gameDescriptionRepo: IGameDescriptionRepo
На уроке как раз про этот момент говорил, что инжектить нужно всегда только в конструктор. Исключение это Android компоненты `Activity`, `Fragment` и тд.

2021-08-31 19:02 UTC, PeterBukhal-Geekbrains commented on CourseProject/app/src/main/java/com/example/courseproject/GameDescriptionPresenter.kt
> +        gameDescriptionRepo.getGameDescription(id)
Упущен важный момент про который мы говорили на вебинаре, это отмена цепочки в случае необходимости. В текущем виде этот момент не реализован, нужно использовать `Disposable` и отменить цепочку как минимум в методе презентера `onDestroy`.

2021-08-31 19:02 UTC, PeterBukhal-Geekbrains commented on CourseProject/app/src/main/java/com/example/courseproject/GameDescriptionPresenter.kt
> +    fun backPressed(): Boolean {
в Cicerone возврат назад и так работает прекрасно без всяких) просто убери и используй правильныйе команды router`a

2021-09-06 08:12 UTC, PeterBukhal-sovcombank requested changes
Есть критические замечания. Пока не принимаю. Не поправлены многие замечания прошлых ревью

2021-09-06 08:12 UTC, PeterBukhal-sovcombank commented on CourseProject/app/src/main/java/com/example/courseproject/AndroidScreens.kt
> +    fun gameDescription(id:Int?)=FragmentScreen {GameDescriptionFragment.newInstance(id!!)}
Не нужно злоупотреблять опционалами (‘?’) и форсанрапами (‘!!’), в этом смысла нет, лучше проверять на этот момент еще раньше до вызова.

2021-09-07 17:25 UTC, merged